name: Deploy Dev

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn install

      - name: Build for GitHub
        run: yarn build

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          BRANCH: gh-pages
          FOLDER: dist

